### ISSUE TITLE
commons-dbcp-1.4-monitored.jar doesn't output monitored stats to log file?

### ISSUE THREAD

**Issue by cyu021** [nicolas-raoul/threadsStatsGraph#1]
Hi,

I have already replaced the common "commons-dbcp-1.4.jar" with "commons-dbcp-1.4-monitored.jar", and I am unable to tell whether it works since I cannot find any line starts with "DBCPMONITOR;".
I have two deployments.  One is deployed as standalone JVM, and the other is deployed to Websphere Application Server (WAS) JVM.  Both running JDK 1.7 and built with Spring framework.  How do I enable the monitoring feature?

Thanks.

I checked my log files with the following commands:
### daemon log

$ tail -50000 daemon.log | grep DBCPMONITOR;
<img width="541" alt="screen shot 2015-10-20 at 2 29 39 pm" src="https://cloud.githubusercontent.com/assets/437295/10599722/54de12c0-7737-11e5-83cf-0ab167d828fc.png">
### WAS log

$ tail -50000 SystemOut.log | grep DBCPMONITOR;
<img width="549" alt="screen shot 2015-10-20 at 2 30 11 pm" src="https://cloud.githubusercontent.com/assets/437295/10599725/5c2524ec-7737-11e5-9e3d-374340395c5b.png">

**Comment by nicolas-raoul** [comment]
Sorry for the wrong URL, could you please post at https://github.com/nicolas-raoul/Commons-DBCP-monitoring/issues/new instead?
Thanks!
